In [2]:
import numpy as np
import pandas as pd

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.full(5, 1.5)

array([1.5, 1.5, 1.5, 1.5, 1.5])

In [10]:
np.arange(3, 15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
[*range(3, 15)]

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [18]:
[*range(3, 15, 2)]

[3, 5, 7, 9, 11, 13]

In [28]:
np.linspace(0, 4, 8)

array([0.        , 0.57142857, 1.14285714, 1.71428571, 2.28571429,
       2.85714286, 3.42857143, 4.        ])

In [45]:
np.random.rand(3, 3)

array([[0.52667329, 0.2668143 , 0.08814118],
       [0.26760167, 0.38308843, 0.25889008],
       [0.94501132, 0.82948445, 0.12095803]])

In [47]:
np.random.seed(2)
np.random.rand(3, 3)

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

In [68]:
np.random.randint(low=40, high=100, size=(3, 3))

array([[62, 46, 59],
       [96, 58, 41],
       [44, 80, 57]])

In [75]:
a = np.random.rand(5)
a *= 10
b = np.random.rand(5)
b *= 10

In [79]:
a

array([9.7291069 , 1.12776215, 3.13258528, 0.4179771 , 7.38399759])

In [80]:
b

array([6.57512388, 2.14635746, 4.1675344 , 6.43841934, 6.61481327])

In [77]:
a > b

array([ True, False, False, False,  True])

In [81]:
a[a > b]

array([9.7291069 , 7.38399759])

In [3]:
I = np.eye(3)

In [4]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])

In [6]:
I.dot(V)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [8]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [10]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [1, 1, 2]
])

In [29]:
V[1:, :]

array([[0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [1. , 1. , 2. ]])

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head(3)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350